### PR TITLE
Suggested Improvements

### PR DESCRIPTION
**Pull request by jneilliii**
Replace default GCODE viewmodel with PrettyGCode
Changed navbar injector into generic template

### CODE REVIEW

**Comment by Kragrathea** [comment]
Hi Jneilliii. Sorry for the late reply. For some reason I just got the pull notification. 

What does this change do exactly?

**Comment by jneilliii** [comment]
I just submitted it today. Basically what it will do is completely replace the default GCODE Viewer tab with your Pretty GCode tab, but retain the name of GCODE Viewer on the tab name. I think yours is way better than the default one and I don't see any reason to keep both loaded on the page.

**Comment by Kragrathea** [comment]
Well thanks. :-) 

But I think such a change should at least be optional. PGCode takes a lot more resources than the default one. And I can see wanting to check progress on say my phone occasionally. 

I wonder if the same result (effectively removing the old tab and renaming PCcode tab) couldn't be done using the CSS box in the options.

**Comment by jneilliii** [comment]
Here's a screenshot of what I mean. Only thing that may need to be looked into is why the box got stretched, unless that's unexpected.

image

**Comment by jneilliii** [comment]
Good point. I could definitely go that route as well of hiding the tab as an option versus completely replacing. Was just thinking this was an easier solution for now. You are right though, it does seem to bog down the interface a little versus the 2d, but really just on initial load. Maybe incorporating some form of dynamic loading would help with that, similar to how OctoPrint does with the webcam tab. The video is only loaded/shown when on that tab.

**Comment by Kragrathea** [comment]
I do defer as much loading and setup as possible until you actually switch to the tab. Maybe it could be better tho. 

CSS to hide the existing GCode tab is pretty easy. (#gcode_link{display:none;}) But I am not sure how or if you can change the order of the tabs.  Even in Octoprint I am not sure how they decide to order them or when they appear in the drop down.

**Comment by jneilliii** [comment]
I've got two plugins that will do that re-ordering by updating the correct
section in config.yaml. Both TabOrder and DragonOrder will do the moving
around.

**Pull request closed without merging**
