### PR TITLE
Add G2/G3 Support

### LINKED ISSUE #52: Wrong rendering of G2 and G3 gcodes
With G2 and G3 moves picture gets corrupted. 
E.g. G code  processed with ArcWelder in Octoprint:
PrettyGcode_G2_G3_errors

### PR DESCRIPTION
**Pull request by FormerLurker**
Adds support for G2/G3.  There are a few constants that can be used to adjust the rendering to match Marlin firmware (but not 100% of the options have been added yet).  R and K are not yet supported since I don't know how K works (not in the docs I've seen) and I have no code with which to test R.  There is some code commented out that should be close, but needs to be debugged.  Let me know if anything needs modification, or if you need gcode to test it.  You could always install arc welder and use that to generate arcs in X Y Z I J E F form.

I hope this relieves you of some issues caused by my plugin :)

Resolves #52.

### CODE REVIEW

**Comment by FormerLurker** [comment]
OK, sorry, I have no idea why those other commits are showing up.  Hopefully you can do a squash and merge or something :(

Let me know if I need to do anything different.  I'm still learning github after 3 years of working with it.

**Comment by Kragrathea** [comment]
Looks good! The merge stuff is just Github being weird I think. 

There is actually one more part to this I forgot. The G2/G3 commands should also be segmented in the PrintheadSimulator "class" addCommand() function. This is what animates the printhead when you are printing. As it is currently it will probably just move in a straight line instead of an arc. 

That said, I am OK with that behavior for now. Its enough to have the arcs displayed correctly.  Do you still want me to pull this change?

**Comment by FormerLurker** [comment]
Why don't you pull this one, and I will work on the simulator bit next and submit another pr?

**Comment by Kragrathea** [comment]
Done. I'll do a new release in a few days. I want to see if there are any issues with the release I just did.

**Comment by FormerLurker** [comment]
I know how that goes.  No nees to rush anything.

**Pull request merged**
